### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jucasoliveira** [jucasoliveira/terminalGPT#3]
- [x] Encrypt file to allow only nodejs to read the apiKey
- [x] Add loader for the async request to openAi
- [ ] Save chat
- [ ] add ability to send the context of the conversation and receive a better response
- [x] create NPM package of the project
