### ISSUE TITLE
TODO 3 : CI/CD

### ISSUE THREAD

**Issue by jucasoliveira** [jucasoliveira/terminalGPT#7]
- [ ] Add CI/CD
- [x] When a user creates PR for the main, GitHub actions will run the test, if any error, block the PR
- [ ] When a PR is merged, bump the package JSON version, create a tag for the version and npm publish
    - [ ] Configure GitHub secrets, with npm keys
